version: 0.2

phases:
  install:
    commands:
      - pip install --upgrade awscli
      - aws --version
  pre_build:
    commands:
      - echo Logging in to Amazon EKS...
      - aws eks --region $AWS_DEFAULT_REGION update-kubeconfig --name $AWS_CLUSTER_NAME
      - aws eks --region us-east-1 update-kubeconfig --name fcmb-cluster
      - kubectl config current-context # Verify the current context is correctly set
      - echo check config 
      - kubectl config view --minify
      - echo check kubectl access
      - kubectl apply -f deployment.yaml
      - kubectl rollout restart -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl get svc my-app-service
